# Generated by Django 3.1.7 on 2021-02-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=30)),
                ('option2', models.CharField(max_length=30)),
                ('option3', models.CharField(max_length=30)),
                ('option1c', models.IntegerField(default=0)),
                ('option2c', models.IntegerField(default=0)),
                ('option3c', models.IntegerField(default=0)),
            ],
        ),
    ]
