# Generated by Django 3.1.7 on 2021-02-24 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollmodel',
            old_name='option1c',
            new_name='vote1',
        ),
        migrations.RenameField(
            model_name='pollmodel',
            old_name='option2c',
            new_name='vote2',
        ),
        migrations.RenameField(
            model_name='pollmodel',
            old_name='option3c',
            new_name='vote3',
        ),
    ]
